require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FastaDataController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # FastaDatum. As you add validations to FastaDatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    content1 = "ABCDEFG1\nBCDEFGH1"
    {filename: 'test1.fasta', data: content1}
  }

  let(:invalid_attributes) {
    content1 = ''
    {filename: '', data: content1}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FastaDataController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fasta_data as @fasta_data" do
      FastaDatum.destroy_all
      fasta_datum = FastaDatum.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fasta_data)).to eq([fasta_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested fasta_datum as @fasta_datum" do
      fasta_datum = FastaDatum.create! valid_attributes
      get :show, {:id => fasta_datum.to_param}, valid_session
      expect(assigns(:fasta_datum)).to eq(fasta_datum)
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fasta_datum" do
      fasta_datum = FastaDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => fasta_datum.to_param}, valid_session
      }.to change(FastaDatum, :count).by(-1)
    end

    it "redirects to the fasta_data list" do
      fasta_datum = FastaDatum.create! valid_attributes
      delete :destroy, {:id => fasta_datum.to_param}, valid_session
      expect(response).to redirect_to(fasta_data_url)
    end
  end

end
